/**
 * Client for the desktop app's own changelog (ADR 0036) —
 * `https://getsilo.dev/changelog.json`, a structured JSON copy of
 * `apps/desktop/CHANGELOG.md` generated by `apps/docs/scripts/copy-changelog.mjs`.
 * Feeds the update-available modal's changelog section (`UpdateService.getChangelog`).
 * Mirrors `registry-client.ts`'s ETag-cache pattern.
 *
 * @internal
 */
import { compareVersions } from "./registry-client";

/** One version's changelog section. */
export interface ChangelogEntry {
  version: string;
  date: string;
  body: string;
}

const CHANGELOG_URL = "https://getsilo.dev/changelog.json";

interface ChangelogIndex {
  schemaVersion: number;
  entries: ChangelogEntry[];
}

/** Drop malformed entries rather than failing the whole fetch. */
function parseChangelogIndex(raw: unknown): ChangelogIndex {
  const obj = raw as Partial<ChangelogIndex> | null;
  if (!obj || typeof obj !== "object" || !Array.isArray(obj.entries)) {
    throw new Error("changelog.json is malformed (no entries array)");
  }
  const entries: ChangelogEntry[] = [];
  for (const e of obj.entries as Partial<ChangelogEntry>[]) {
    if (typeof e?.version === "string" && typeof e.body === "string") {
      entries.push({
        version: e.version,
        date: typeof e.date === "string" ? e.date : "",
        body: e.body,
      });
    }
  }
  return {
    schemaVersion:
      typeof obj.schemaVersion === "number" ? obj.schemaVersion : 1,
    entries,
  };
}

// ETag cache per URL: steady-state re-fetches are zero-body 304s.
const cache = new Map<
  string,
  { etag: string | null; entries: ChangelogEntry[] }
>();

/** Fetch (or revalidate) changelog.json. Throws on network/HTTP/parse failure — callers fall back. */
export async function fetchChangelog(
  url: string = CHANGELOG_URL,
): Promise<ChangelogEntry[]> {
  const cached = cache.get(url);
  const headers: Record<string, string> = {};
  if (cached?.etag) headers["if-none-match"] = cached.etag;

  const resp = await fetch(url, { headers });
  if (resp.status === 304 && cached) return cached.entries;
  if (!resp.ok) throw new Error(`changelog fetch ${url} → HTTP ${resp.status}`);
  const { entries } = parseChangelogIndex(await resp.json());
  cache.set(url, { etag: resp.headers.get("etag"), entries });
  return entries;
}

/** Test hook: drop the ETag cache. @internal */
export function clearChangelogCache(): void {
  cache.clear();
}

/**
 * Entries strictly newer than `installedVersion` and up to and including
 * `availableVersion`, newest first.
 */
export function changelogRange(
  entries: readonly ChangelogEntry[],
  installedVersion: string,
  availableVersion: string,
): ChangelogEntry[] {
  return entries
    .filter(
      (e) =>
        compareVersions(e.version, installedVersion) > 0 &&
        compareVersions(e.version, availableVersion) <= 0,
    )
    .sort((a, b) => compareVersions(b.version, a.version));
}
