import type { Extension, ThemePreset } from "@silo-code/sdk";

// Built-in theme presets, contributed through `ctx.theme.registerPreset`. Core
// ships only Dark and Light (see layout/presets CORE_PRESETS); everything here
// is a regular contribution — the same path a third-party extension would use.
// These move out of core so the picker's bundled themes are independently
// removable and so theming is a real contribution point, not a core list.
// Listed alphabetically by name; keep new entries in that order.
const PRESETS: ThemePreset[] = [
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    base: "dark",
    colorScheme: "dark",
    vars: {
      "--silo-color-bg": "#1d2021",
      "--silo-color-bg-hover": "#3c3836",
      "--silo-color-bg-active": "#665c5466",
      "--silo-color-button-bg": "#504945",
      "--silo-color-button-text": "#a89984",
      "--silo-color-text-hi": "#a89984",
      "--silo-color-text": "#928374",
      "--silo-color-text-lo": "#5f564d",
      "--silo-color-input-bg": "#282828",
      "--silo-color-input-border": "#453f3b",
      "--silo-color-input-text": "#ebdbb2",
      "--silo-color-border": "transparent",
      "--silo-color-border-strong": "#7c6f64",
      "--silo-color-accent": "#83a598",
      "--silo-color-accent-2": "#d3869b",
      "--silo-content-text": "#ebdbb2",
      "--silo-content-editor-text-dim": "#d5c4a1",
      "--silo-content-editor-text-faint": "#a89984",
      "--silo-color-ok": "#b8bb26",
      "--silo-color-warn": "#fabd2f",
      "--silo-color-err": "#fb4934",
      "--silo-content-tab-tray-bg": "#1d2021",
      "--silo-content-tab-tray-text": "#a89984",
      "--silo-content-tab-text-inactive": "#7c6f64",
      "--silo-content-tab-text": "#a89984",
      "--silo-content-tab-text-active": "#ebdbb2",
      "--silo-statusbar-bg": "#1a1c1d",
      "--silo-statusbar-text": "#a89984",
      // Notify (toast) — a warm brown card from the theme's own family, lighter
      // than the app bg so it lifts, darker than the buttons (#504945) so they
      // read; cream text to match.
      "--silo-notify-bg": "#3a3634",
      "--silo-notify-text": "#d5c4a1",
      "--silo-notify-text-hi": "#ebdbb2",
    },
  },
  {
    id: "high-contrast-dark",
    name: "High Contrast Dark",
    base: "dark",
    colorScheme: "dark",
    // Inherit Dark's panel/accent palette; brighten text for legibility, and
    // lift hover/active fills a step above core Dark (#282d3a) so selected
    // rows read clearly against #161922 without jumping far from Dark's slate.
    vars: {
      "--silo-color-bg-hover": "#2a3144",
      "--silo-color-bg-active": "#343c52",
      "--silo-color-button-text": "#e4e6ec",
      "--silo-color-text-hi": "#e4e6ec",
      "--silo-color-text": "#a0a0a0",
      "--silo-color-text-lo": "#6b6b6b",
      "--silo-color-input-bg": "#2a3044",
      "--silo-color-input-text": "#f5f6fa",
      "--silo-color-input-border": "#4a5378",
      "--silo-color-toolbar-text": "#f0f0f0",
      "--silo-color-toolbar-text-disabled": "#a8a8a8",
      "--silo-color-content-text": "#f5f6fa",
      "--silo-content-text": "#f5f6fa",
      "--silo-content-editor-text-dim": "#c7cbdb",
      "--silo-content-editor-text-faint": "#9aa0bd",
      "--silo-content-tab-tray-text": "#a8a8a8",
      "--silo-content-tab-text-inactive": "#a8a8a8",
      "--silo-content-tab-text": "#a8a8a8",
      "--silo-content-tab-text-active": "#f5f5f5",
      "--silo-statusbar-text": "#e4e6ec",
      "--silo-tab-text-active": "#f5f5f5",
      "--silo-tab-text": "#a8a8a8",
      "--silo-tab-bg-hover": "#2a3144",
      "--silo-notify-text": "#e4e7ee",
      "--silo-notify-text-hi": "#ffffff",
    },
  },
  {
    id: "high-contrast-light",
    name: "High Contrast Light",
    base: "light",
    colorScheme: "light",
    // Light counterpart: inherit Light's panel/accent, darken text, and deepen
    // hover/active fills so selection reads against #e5e5e5.
    vars: {
      "--silo-color-bg-hover": "#d8d8d8",
      "--silo-color-bg-active": "#b8d4f0",
      "--silo-color-button-text": "#1a1a1a",
      "--silo-color-text-hi": "#1a1a1a",
      "--silo-color-text": "#3a3a3a",
      "--silo-color-text-lo": "#5a5a5a",
      "--silo-color-input-text": "#0a0a0a",
      "--silo-color-input-border": "#6b6b6b",
      "--silo-color-toolbar-text": "#0a0a0a",
      "--silo-color-toolbar-text-disabled": "#3a3a3a",
      "--silo-color-content-text": "#050505",
      "--silo-content-text": "#050505",
      "--silo-content-editor-text-dim": "#2e2e2e",
      "--silo-content-editor-text-faint": "#4a4a4a",
      "--silo-content-tab-tray-text": "#1a1a1a",
      "--silo-content-tab-text-inactive": "#2e2e2e",
      "--silo-content-tab-text": "#1a1a1a",
      "--silo-content-tab-text-active": "#000000",
      "--silo-statusbar-text": "#1a1a1a",
      "--silo-tab-text-active": "#000000",
      "--silo-tab-text": "#1a1a1a",
      "--silo-tab-bg-hover": "#d8d8d8",
      "--silo-notify-text": "#1a1a1a",
      "--silo-notify-text-hi": "#000000",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    base: "dark",
    colorScheme: "dark",
    vars: {
      "--silo-color-bg": "#002b36",
      "--silo-color-bg-hover": "#073642",
      "--silo-color-bg-active": "#586e7566",
      "--silo-color-button-bg": "#073642",
      "--silo-color-button-text": "#839496",
      "--silo-color-text-hi": "#93a1a1",
      "--silo-color-text": "#839496",
      "--silo-color-text-lo": "#586e75",
      "--silo-color-input-bg": "#073642",
      "--silo-color-input-border": "#0f4c5b",
      "--silo-color-input-text": "#93a1a1",
      "--silo-color-border": "transparent",
      "--silo-color-border-strong": "#586e75",
      "--silo-color-accent": "#cb4b16",
      "--silo-color-accent-2": "#6c71c4",
      // Dark's default paints the primary label in the page bg, which works for
      // the light-neutral accents the other dark themes use. Solarized's accent
      // is a saturated orange, where white is the legible side (4.6:1 vs 3.3:1).
      "--silo-button-primary-text": "#fff",
      "--silo-content-text": "#839496",
      "--silo-content-editor-text-dim": "#657b83",
      "--silo-content-editor-text-faint": "#586e75",
      "--silo-color-ok": "#859900",
      "--silo-color-warn": "#b58900",
      "--silo-color-err": "#dc322f",
      "--silo-content-tab-bg": "#002b36",
      "--silo-content-tab-tray-bg": "#002b36",
      "--silo-content-tab-tray-text": "#839496",
      "--silo-content-tab-text-inactive": "#586e75",
      "--silo-content-tab-text": "#839496",
      "--silo-content-tab-text-active": "#93a1a1",
      "--silo-content-editor-bg": "#002b36",
      "--silo-content-terminal-bg": "#002b36",
      "--silo-color-toolbar-bg": "#002b36",
      "--silo-color-toolbar-text": "#839496",
      "--silo-color-toolbar-text-disabled": "#586e75",
      "--silo-statusbar-bg": "#00252e",
      "--silo-statusbar-text": "#839496",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    base: "light",
    colorScheme: "light",
    vars: {
      "--silo-color-bg": "#eee8d5",
      "--silo-color-bg-hover": "#e8e2d0",
      "--silo-color-bg-active": "#ddd8c0",
      "--silo-color-button-bg": "#d6cfbd",
      "--silo-color-button-text": "#657b83",
      "--silo-color-text-hi": "#839496",
      "--silo-color-text": "#738a8a",
      "--silo-color-text-lo": "#a3b1b1",
      "--silo-color-input-bg": "#fdf6e3",
      "--silo-color-input-border": "#cfc8b3",
      "--silo-color-input-text": "#657b83",
      "--silo-color-border": "#eee8d5",
      "--silo-color-border-strong": "#93a1a1",
      "--silo-color-accent": "#d25f26ff",
      "--silo-color-accent-2": "#6c71c4",
      "--silo-content-text": "#657b83",
      "--silo-content-editor-text-dim": "#839496",
      "--silo-content-editor-text-faint": "#93a1a1",
      "--silo-color-ok": "#859900",
      "--silo-color-warn": "#b58900",
      "--silo-color-err": "#dc322f",
      "--silo-content-tab-bg": "#fdf6e3",
      "--silo-content-tab-tray-bg": "#eee8d5",
      "--silo-content-tab-tray-text": "#839496",
      "--silo-content-tab-text-inactive": "#93a1a1",
      "--silo-content-tab-text": "#657b83",
      "--silo-content-tab-text-active": "#586e75",
      "--silo-content-editor-bg": "#fdf6e3",
      "--silo-content-terminal-bg": "#fdf6e3",
      "--silo-color-toolbar-bg": "#fdf6e3",
      "--silo-color-toolbar-text": "#657b83",
      "--silo-color-toolbar-text-disabled": "#839496",
      "--silo-statusbar-bg": "#eee8d5",
      "--silo-statusbar-text": "#839496",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    base: "dark",
    colorScheme: "dark",
    vars: {
      "--silo-color-bg": "#16161e",
      "--silo-color-bg-hover": "#1f2335",
      "--silo-color-bg-active": "#364a8266",
      "--silo-color-button-bg": "#24283b",
      "--silo-color-button-text": "#787c99",
      "--silo-color-text-hi": "#787c99",
      "--silo-color-text": "#6b7099",
      "--silo-color-text-lo": "#434a6b",
      "--silo-color-input-bg": "#20243a",
      "--silo-color-input-border": "#333959",
      "--silo-color-input-text": "#a9b1d6",
      "--silo-color-border": "transparent",
      "--silo-color-border-strong": "#3d4461",
      "--silo-color-accent": "#7aa2f7",
      "--silo-color-accent-2": "#bb9af7",
      "--silo-content-text": "#a9b1d6",
      "--silo-content-editor-text-dim": "#787c99",
      "--silo-content-editor-text-faint": "#565f89",
      "--silo-color-ok": "#9ece6a",
      "--silo-color-warn": "#e0af68",
      "--silo-color-err": "#f7768e",
      "--silo-content-tab-tray-bg": "#16161e",
      "--silo-content-tab-tray-text": "#787c99",
      "--silo-content-tab-text-inactive": "#565f89",
      "--silo-content-tab-text": "#787c99",
      "--silo-content-tab-text-active": "#a9b1d6",
      "--silo-statusbar-bg": "#131319",
      "--silo-statusbar-text": "#787c99",
      "--silo-tab-text-active": "#a9b1d6",
      "--silo-tab-text": "#787c99",
      "--silo-tab-bg-hover": "#1f2335",
      "--silo-tab-border-active": "#3d4461",
    },
  },
];

export const extension: Extension = {
  id: "silo.theme-presets",
  manifest: {
    name: "Theme Presets",
    description: "Built-in color themes for the workbench.",
  },
  activate(ctx) {
    for (const preset of PRESETS) ctx.theme.registerPreset(preset);
  },
};
