import type { Extension, ThemePreset } from "@silo-code/sdk";

// Built-in theme presets, contributed through `ctx.registerThemePreset`. Core
// ships only Dark and Light (see layout/presets CORE_PRESETS); everything here
// is a regular contribution — the same path a third-party extension would use.
// These move out of core so the picker's bundled themes are independently
// removable and so theming is a real contribution point, not a core list.
const PRESETS: ThemePreset[] = [
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    base: "dark",
    colorScheme: "dark",
    vars: {
      "--silo-color-bg": "#16161e",
      "--silo-color-bg-hover": "#1f2335",
      "--silo-color-bg-active": "#364a8266",
      "--silo-color-button-bg": "#24283b",
      "--silo-color-button-text": "#787c99",
      "--silo-color-text-hi": "#787c99",
      "--silo-color-text": "#6b7099",
      "--silo-color-text-lo": "#434a6b",
      "--silo-color-input-bg": "#1f2335",
      "--silo-color-input-text": "#a9b1d6",
      "--silo-color-border": "transparent",
      "--silo-color-border-strong": "#3d4461",
      "--silo-color-accent": "#7aa2f7",
      "--silo-color-accent-2": "#bb9af7",
      "--silo-content-text": "#a9b1d6",
      "--silo-content-editor-text-dim": "#787c99",
      "--silo-content-editor-text-faint": "#565f89",
      "--silo-color-ok": "#9ece6a",
      "--silo-color-warn": "#e0af68",
      "--silo-color-err": "#f7768e",
      "--silo-content-tab-bg": "#1a1b26",
      "--silo-content-tab-tray-bg": "#16161e",
      "--silo-content-tab-tray-text": "#787c99",
      "--silo-content-tab-text-inactive": "#565f89",
      "--silo-content-tab-text": "#787c99",
      "--silo-content-tab-text-active": "#a9b1d6",
      "--silo-statusbar-bg": "#131319",
      "--silo-statusbar-text": "#787c99",
      "--silo-tab-text-active": "#a9b1d6",
      "--silo-tab-text": "#787c99",
      "--silo-tab-bg-hover": "#1f2335",
      "--silo-tab-border-active": "#3d4461",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    base: "light",
    colorScheme: "light",
    vars: {
      "--silo-color-bg": "#eee8d5",
      "--silo-color-bg-hover": "#e8e2d0",
      "--silo-color-bg-active": "#cdc8ae",
      "--silo-color-button-bg": "#d6cfbd",
      "--silo-color-button-text": "#657b83",
      "--silo-color-text-hi": "#839496",
      "--silo-color-text": "#738a8a",
      "--silo-color-text-lo": "#a3b1b1",
      "--silo-color-input-bg": "#e8e2d0",
      "--silo-color-input-text": "#657b83",
      "--silo-color-border": "#eee8d5",
      "--silo-color-border-strong": "#93a1a1",
      "--silo-color-accent": "#d25f26ff",
      "--silo-color-accent-2": "#6c71c4",
      "--silo-content-text": "#657b83",
      "--silo-content-editor-text-dim": "#839496",
      "--silo-content-editor-text-faint": "#93a1a1",
      "--silo-color-ok": "#859900",
      "--silo-color-warn": "#b58900",
      "--silo-color-err": "#dc322f",
      "--silo-content-tab-bg": "#fdf6e3",
      "--silo-content-tab-tray-bg": "#eee8d5",
      "--silo-content-tab-tray-text": "#839496",
      "--silo-content-tab-text-inactive": "#93a1a1",
      "--silo-content-tab-text": "#657b83",
      "--silo-content-tab-text-active": "#586e75",
      "--silo-content-editor-bg": "#fdf6e3",
      "--silo-content-terminal-bg": "#fdf6e3",
      "--silo-breadcrumb-bg": "#fdf6e3",
      "--silo-breadcrumb-text": "#839496",
      "--silo-breadcrumb-text-active": "#657b83",
      "--silo-breadcrumb-icon": "#93a1a1",
      "--silo-statusbar-bg": "#eee8d5",
      "--silo-statusbar-text": "#839496",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    base: "dark",
    colorScheme: "dark",
    vars: {
      "--silo-color-bg": "#1d2021",
      "--silo-color-bg-hover": "#3c3836",
      "--silo-color-bg-active": "#665c5466",
      "--silo-color-button-bg": "#504945",
      "--silo-color-button-text": "#a89984",
      "--silo-color-text-hi": "#a89984",
      "--silo-color-text": "#928374",
      "--silo-color-text-lo": "#5f564d",
      "--silo-color-input-bg": "#3c3836",
      "--silo-color-input-text": "#ebdbb2",
      "--silo-color-border": "transparent",
      "--silo-color-border-strong": "#7c6f64",
      "--silo-color-accent": "#83a598",
      "--silo-color-accent-2": "#d3869b",
      "--silo-content-text": "#ebdbb2",
      "--silo-content-editor-text-dim": "#d5c4a1",
      "--silo-content-editor-text-faint": "#a89984",
      "--silo-color-ok": "#b8bb26",
      "--silo-color-warn": "#fabd2f",
      "--silo-color-err": "#fb4934",
      "--silo-content-tab-bg": "#282828",
      "--silo-content-tab-tray-bg": "#1d2021",
      "--silo-content-tab-tray-text": "#a89984",
      "--silo-content-tab-text-inactive": "#7c6f64",
      "--silo-content-tab-text": "#a89984",
      "--silo-content-tab-text-active": "#ebdbb2",
      "--silo-statusbar-bg": "#1a1c1d",
      "--silo-statusbar-text": "#a89984",
      // Notify (toast) — a warm brown card from the theme's own family, lighter
      // than the app bg so it lifts, darker than the buttons (#504945) so they
      // read; cream text to match.
      "--silo-notify-bg": "#3a3634",
      "--silo-notify-text": "#d5c4a1",
      "--silo-notify-text-hi": "#ebdbb2",
    },
  },
];

export const extension: Extension = {
  id: "silo.theme-presets",
  activate(ctx) {
    for (const preset of PRESETS) ctx.registerThemePreset(preset);
  },
};
